apiVersion: apps/v1
kind: Deployment
metadata:
  name: learnk8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: learnk8s
  template:
    metadata:
      labels:
        app: learnk8s
    spec:
      containers:
        - name: learnk8s
          image: werelay/learnk8s:latest
          ports:
            - containerPort: 8080
